### PR TITLE
1st pass adding Jekyll theme

### PR DESCRIPTION
**Pull request by sghoweri**
Adding basic theme to close out https://github.com/drupal-pattern-lab/drupal-pattern-lab.github.io/issues/9

Took the out of the box Jekyll Cayman theme, broke the theme's Sass into ITCSS-based partials with BEMIT prefixes, and wired that all up to the templating base we already had. Oh, and added a couple dynamic links in the header.

Had to rush to get this pushed up before I'm offline doing a bunch of tours later today so I'm definitely fine treating this as just a rough first pass -- any feedback would be much appreciated!

Side note: besides breaking some of these templates out into partials, asyncing the web fonts properly, and redoing the default variables / mixins, I feel like this is already almost at the point where a proper Gulp build would be more appropriate (ex. autoprefixer).

### CODE REVIEW

**Comment by evanmwillhite** [comment]
This looks great to me. I'm fine shipping as-is and adding a Gulp setup later, but I could be persuaded otherwise. :)

**Review by evanmwillhite — APPROVED** [review]

**Review by EvanLovely — APPROVED** [review]
Looks great; nice work! I added a few tweaks in some commits. Feel free to merge after you've had a look over them.

**Comment by EvanLovely** [comment]
Also, I don't know if we can add Gulp without committing compiled assets due to us using GitHub pages. Personally, I think the constraint of having to use just GitHub pages and Jekyll would be good for us as this repo has just a content distribution goal and we don't want to over-engineer it: we've got to save that time for our other repos.

**Comment by sghoweri** [comment]
@EvanLovely Sweet - thanks! 

Yeah, I gotta agree. Let's stick with simplicity for this repo for now and should we need / want something more robust, maybe that'd be a good place to use the work that we're doing in a more real world example.

**Pull request merged**
